config/routes.rb
Rails.application.routes.draw do
  root :to => 'shop#home' 

  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :offers do
    get 'switch', :on => :member
  end

  get 'click/:offer_id', to: 'shop#click', as: 'click'
  # to make ours links more user friendly
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/offer.rb
class Offer < ApplicationRecord
  has_many :offers_users, dependent: :destroy
  has_many :users, through: :offers_users

  validates :advertiser_name, uniqueness: true, presence: true
  validates :url, url: true
  validates :description, length: { maximum: 500 }

  attribute :enabled, :boolean, default: -> { false }
  attribute :premium, :boolean, default: -> { false }

  scope :enabled, -> { where(enabled: true) }
  scope :disabled, -> { where(enabled: false) }
  scope :premium, -> { where(premium: true) }

  def self.status_updater
    to_enable = Offer.disabled.where('starts_at < :now and ends_at > :now', now: Time.zone.now)
    to_enable.update_all(enabled: true)

    to_disable = Offer.enabled.where('ends_at < ?', Time.zone.now)
    to_disable.update_all(enabled: false)

    Rails.logger.info("#{to_enable.count} offers enabled, #{to_disable.count} offers disabled")
  end

  # gives 'https://' to url if needed
  def url=(url_str)
    unless url_str.blank?
      unless url_str.split(':')[0] == 'http' || url_str.split(':')[0] == 'https'
        url_str = 'https://' + url_str
      end
    end
    write_attribute :url, url_str
  end
end

app/models/offers_user.rb
class OffersUser < ApplicationRecord
  belongs_to :user
  belongs_to :offer

  validates :offer_id, uniqueness: { scope: :user }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :offers_users, dependent: :destroy
  has_many :offers, through: :offers_users

  has_secure_password

  validates :email, presence: true, uniqueness: true
  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end

  include Pagy::Backend
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:switch, :edit, :update, :destroy]

  # GET /offers
  # GET /offers.json
  def index
    @offers = Offer.all
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
    @offer = Offer.find params[:id]
  end

  # GET /offers/1/switch
  def switch
    @offer.toggle(:enabled)
    save_worked = @offer.save

    if save_worked
      flash[:success] = "#{@offer.advertiser_name} sucefully updated"
    else
      flash[:error] = "#{@offer.advertiser_name} update failed   with errors: #{@offer.errors.messages}"
    end
    redirect_to action: 'index'
  end

  # GET /offers/new
  def new
    @offer = Offer.new
  end 

  # GET /offers/1/edit
  def edit
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = Offer.new(offer_params)

    respond_to do |format|
      if @offer.save
        format.html { redirect_to @offer, notice: 'Offer was successfully created.' }
        format.json { render :show, status: :created, location: @offer }
      else
        format.html { render :new }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
        format.json { render :show, status: :ok, location: @offer }
      else
        format.html { render :edit }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to offers_url, notice: 'Offer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def offer_params
      params.require(:offer).permit(:advertiser_name, :url, :description, :starts_at, :ends_at, :premium, :enabled)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now[:alert] = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/shop_controller.rb
class ShopController < ApplicationController
  def home
      @pagy, @offers = pagy(Offer.enabled.order(premium: :desc))
  end

  def click
    offer = Offer.find_by(id: params[:offer_id])
    user = current_user

    if offer
      if user && user.offers.exclude?(offer)
        user.offers << offer
      end

      redirect_to(offer.url) and return
    end

    redirect_back(fallback_location: root_path)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def bootstrap_class_for(flash_type)
    case flash_type.to_sym
    when :notice then "alert-info"
    when :success then "alert-success"
    when :error then "alert-danger"
    when :alert then "alert-danger"
    else "alert-#{flash_type}"
    end
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)}", role: "alert") do 
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message 
            end)
    end
    nil
  end
end

app/helpers/offers_helper.rb
module OffersHelper

  def switch_option(enabled)
    if enabled
      'Disable'
    else
      'Enable'
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item">
      <%= link_to "Home", root_path, class: "nav-link" %>
    </li>
  </ul>
  
  <ul class="navbar-nav ml-auto">
    <% if current_user %>
      <li class="nav-item active">
        <span class="navbar-text">
          Logged in as <%= current_user.username %>
        </span>
      </li>
      <li class="nav-item active">
        <%= link_to "Log Out", logout_path, class: "nav-link" %>
      </li>
    <% else %>
      <li class="nav-item active">
        <%= link_to "Sign Up", signup_path, class: "nav-link"  %>
      </li>
      <li class="nav-item active">
        <%= link_to "Log In", login_path, class: "nav-link"  %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cashback</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <div class="container">
      <%= flash_messages %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/offers/_form.html.erb
<%= form_with(model: offer, local: true) do |form| %>
  <% if offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
        <% offer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :advertiser_name %>
    <%= form.text_field :advertiser_name %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :starts_at %>
    <%= form.date_select :starts_at %>
  </div>

  <div class="field">
    <%= form.label :ends_at %>
    <%= form.date_select :ends_at %>
  </div>

  <div class="field">
    <%= form.label :premium %>
    <%= form.check_box :premium %>
  </div>

  <div class="field">
    <%= form.label :enabled %>
    <%= form.check_box :enabled %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/offers/edit.html.erb
<h1>Editing Offer</h1>

<%= render 'form', offer: @offer %>

<%= link_to 'Show', @offer %> |
<%= link_to 'Back', offers_path %>

app/views/offers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Offers</h1>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Advertiser name</th>
      <th>Url</th>
      <th>Description</th>
      <th>Starts at</th>
      <th>Ends at</th>
      <th>Premium</th>
      <th>Enabled</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @offers.each do |offer| %>
      <tr>
        <td><%= offer.advertiser_name %></td>
        <td><%= offer.url %></td>
        <td><%= offer.description %></td>
        <td><%= offer.starts_at %></td>
        <td><%= offer.ends_at %></td>
        <td><%= offer.premium %></td>
        <td><%= offer.enabled %></td>
        <td><%= link_to 'Edit', edit_offer_path(offer) %></td>
        <td><%= link_to switch_option(offer.enabled), switch_offer_path(offer) %></td>
        <td><%= link_to 'Destroy', offer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Offer', new_offer_path %>

app/views/offers/new.html.erb
<h1>New Offer</h1>

<%= render 'form', offer: @offer %>

<%= link_to 'Back', offers_path %>

app/views/offers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Advertiser name:</strong>
  <%= @offer.advertiser_name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @offer.url %>
</p>

<p>
  <strong>Description:</strong>
  <%= @offer.description %>
</p>

<p>
  <strong>Starts at:</strong>
  <%= @offer.starts_at %>
</p>

<p>
  <strong>Ends at:</strong>
  <%= @offer.ends_at %>
</p>

<p>
  <strong>Premium:</strong>
  <%= @offer.premium %>
</p>

<p>
  <strong>Enabled:</strong>
  <%= @offer.enabled %>
</p>

<%= link_to 'Edit', edit_offer_path(@offer) %> |
<%= link_to 'Back', offers_path %>

app/views/shop/_offer_card.html.erb
<div class="col-lg-4 col-md-6 mb-4">
  <div class="card h-100">
    <% if offer.premium %>
      <div class="card-header">
        Premium!
      </div>
    <% end %>

    <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
    <div class="card-body">
      <h4 class="card-title">
        <%= link_to offer.advertiser_name, click_path(offer.id), target: :_blank %>
      </h4>

      <p class="card-text"><%= offer.description %></p>
    </div>
    <% if offer.users.count > 0 %>
    <div class="card-footer">
      <small class="text-muted"> <%= "Users interested: #{offer.users.count}"%> </small>
    </div>
    <% end %>
  </div>
</div>

app/views/shop/home.html.erb
<div class="container">
  <div class="col-lg-12">
    <div class="row">
      <%= render partial: "offer_card", collection: @offers, as: :offer %>
    </div>
  </div>
  
  <%== pagy_bootstrap_nav(@pagy) %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>